project:
  type: book
  execute-dir: project

book:
  title: "Scientific and Symbolic Computing Software"
  author: "Igor Dimitrov"
  date: "5/17/2024"
  chapters:
    - index.qmd
    - reading.qmd
    - sage/trial/notebook.ipynb
    - sage/trial/notes.qmd
    - sage/trial/notes2.qmd
    - sage/bard/01.ipynb
  page-navigation: true
  downloads: pdf

# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



